-- Digital Builders Seed Data
-- This file contains seed data for development and testing
--
-- Currently empty - will be populated after creating Digital Builders database schema.
--
-- To seed the database:
-- 1. Create your schema migrations
-- 2. Add seed data here
-- 3. Run: supabase db reset (seeds automatically)

-- Example seed data structure (to be implemented):
-- INSERT INTO cities (id, name, description) VALUES (...);
-- INSERT INTO districts (id, city_id, name, description) VALUES (...);
-- INSERT INTO jobs (id, district_id, title, description, reward_db_cred, cooldown_minutes) VALUES (...);
